# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    assume_role = {
      role_arn = "arn:aws:iam::{account_id}:role/TerraformAssumedRole"
    }
    bucket  = "donggyu-gitops-state"
    encrypt = true
    key     = "lattice/terraform.tfstate"
    region  = "ap-northeast-2"
  }
}
