# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    assume_role = {
      role_arn = "arn:aws:iam::182024812696:role/TerraformAssumedRole"
    }
    bucket  = "donggyu-gitops-state"
    encrypt = true
    key     = "vpc/terraform.tfstate"
    region  = "ap-northeast-2"
  }
}
